result_limit: 100,
access_type: "groups",
zotero_access_id: "5222465",
collection_id: "PC3BW6EP",
api_key: "6Xgb3XhGjQXwA8NuZgu3bw3s",
keystore_file: "keystore.json",
keystore_filepath: "source/configuration",
bibtex_filepath: "source",
bibtex_filename: "Diplomarbeit_Michael_Graber.bib"